addons:
  apt:
    packages: libgdiplus

matrix:
  include:
    - dist: xenial
      before_script:
        - pwd
        - wget https://github.com/shimat/opencv_files/releases/download/4.0.0.20181202/OpenCV_Ubuntu1804.zip
        - unzip OpenCV_Ubuntu1804.zip -d opencv_ubuntu
        - ls
      script:
        - pwd; ls
        - mkdir src/build && cd $_
        - cmake -D CMAKE_INSTALL_PREFIX=../../opencv_ubuntu ..
        - make -j4 && make install

notifications:
  email:
    - schimatk@gmail.com